application:
  name: spring-boot-cassandra
server:
  port: 4041
# Following are Cassandra Configuration
cassandra:
  host: 127.0.0.1:9042
  cluster:
    name: test
    username: cassandra
    password: cassandra
  keyspace:
    name: vehicle_tracker